/** Coding Workflow adapter over the Runtime-owned Actor control plane. */

import type {
  AgentActorClient,
  AgentCapabilities,
  AgentEvent,
  AgentExecutionInput,
  AgentExecutionKind,
  AgentExecutionResult,
  AgentMetadataValue,
  AgentTurnExecutor,
} from '@kodax-ai/agent';
import { execFile } from 'node:child_process';
import { assertNoGitInstallPrompt } from '@kodax-ai/agent';
import path from 'node:path';
import { promisify } from 'node:util';
import { emitKodaXDiagnostic } from '@kodax-ai/agent';
import type {
  WorkflowAgentBackend,
  WorkflowSpawnAgentInput,
  WorkflowTaskHandle,
  WorkflowTaskResult,
  WorkflowTaskSummaryEventUpdate,
  WorkflowTaskSnapshot,
  WorkflowTaskStatus,
  WorkflowTaskVerification,
  WorkflowTaskVerificationResult,
  WorkflowWaitOptions,
} from '@kodax-ai/agent';

import { executeChildAgents, assertValidWorkflowEvidenceRefs } from '../child-executor.js';
import type { ChildExecutorOptions } from '../child-executor.js';
import {
  listCodingDispatchableAgents,
  resolveCodingDispatchableAgent,
} from '../external-agents/local-catalog.js';
import {
  constructedAgentToolCeiling,
  resolveConstructedAgentEntry,
} from '../construction/agent-resolver.js';
import { assertSupportedOutputSchema } from './structured-output.js';
import type {
  KodaXChildContextBundle,
  KodaXChildExecutionResult,
  KodaXChildRouteFacts,
  KodaXActorHost,
  KodaXEvents,
  KodaXToolExecutionContext,
  KodaXWireReasoningEffort,
} from '../types.js';

type WorkflowChildSnapshotStatus = 'running' | 'completed' | 'failed' | 'aborted';

const execFileAsync = promisify(execFile);
const GIT_STATUS_TIMEOUT_MS = 10_000;
const DEFAULT_VERIFICATION_REPAIR_ATTEMPTS = 2;
const MUTATING_TOOL_NAMES = new Set(['write', 'edit', 'multi_edit', 'insert_after_anchor']);
const READING_TOOL_NAMES = new Set(['read']);

function intersectWorkflowToolCeilings(
  requested: readonly string[],
  parent: readonly string[],
): readonly string[] {
  if (parent.includes('*')) return requested;
  if (requested.includes('*')) return parent;
  const parentSet = new Set(parent);
  return requested.filter((tool) => parentSet.has(tool));
}
const PREPARATORY_FINAL_TEXT_RE =
  /^\s*(?:let me|i will|i'll|i am going to)\b[\s\S]{0,120}\b(?:start|create|implement|write|build|plan)\b|^\s*(?:我将|让我|接下来)[\s\S]{0,80}(?:开始|创建|编写|实现|制定)/i;

/** The subset of `ChildExecutorOptions` the caller fixes once per run. */
export type WorkflowChildOptions = Omit<
  ChildExecutorOptions,
  | 'maxParallel'
  | 'abortSignal'
  | 'workflowChild'
  | 'workflowDigestMode'
  | 'onWorkflowChildDigest'
  | 'workflowCorrelation'
>;

export interface CodingWorkflowBackendDeps {
  /** Parent tool-execution context carrying the Workflow owner's Actor binding. */
  readonly ctx: KodaXToolExecutionContext;
  /** Fixed per-run child options (parentRole / parentHarness / parentOptions
   *  / maxIterationsPerChild / guardrails / …). */
  readonly childOptions: WorkflowChildOptions;
  /** Seam: child runner. Defaults to `executeChildAgents`. */
  readonly runChild?: (
    bundles: readonly KodaXChildContextBundle[],
    ctx: KodaXToolExecutionContext,
    options: ChildExecutorOptions,
  ) => Promise<KodaXChildExecutionResult>;
  /** Seam: unique child id generator. */
  readonly generateId?: () => string;
  /** Workflow run id for correlating child-agent SDK callbacks. */
  readonly runId?: string;
  /** Default child write policy from the workflow manifest. */
  readonly defaultChildReadOnly?: boolean;
  /** Seam: workspace changed path reader. Defaults to git status/diff. */
  readonly listChangedFiles?: (ctx: KodaXToolExecutionContext) => Promise<readonly string[]>;
  readonly onTaskSummary?: (taskId: string, update: WorkflowTaskSummaryEventUpdate) => void;
  /** True only for scripts generated by KodaX in this run; never inferred from schema content. */
  readonly kodaxAuthored?: boolean;
}

interface WorkflowStepBinding {
  readonly name: string;
  readonly input: WorkflowSpawnAgentInput;
  readonly bundle: KodaXChildContextBundle;
  readonly actorPath: string;
  turnId: string;
  promise?: Promise<KodaXChildExecutionResult>;
  readonly runBundle: (
    bundle: KodaXChildContextBundle,
    execution: AgentExecutionInput,
    actorControl: AgentActorClient,
  ) => Promise<KodaXChildExecutionResult>;
  readonly external: boolean;
  readonly verification?: WorkflowTaskVerification;
  readonly changedPathBaseline: Promise<ChangedPathSnapshot>;
  readonly mutationRecorder: MutationRecorder;
  readonly acceptToolMutationEvidence: boolean;
  repairAttempts: number;
}

interface ChangedPathSnapshot {
  readonly paths: readonly string[];
  readonly error?: string;
}

interface MutationRecorder {
  readonly toolNameById: Map<string, string>;
  readonly toolPathById: Map<string, string>;
  readonly succeededToolCalls: string[];
  readonly succeededPaths: string[];
  readonly readPathById: Map<string, string>;
  readonly succeededReadPaths: string[];
}

interface ResolvedVerification {
  readonly verification?: WorkflowTaskVerification;
}

function normalizeWaitTimeoutMs(opts: WorkflowWaitOptions | undefined): number | undefined {
  if (opts?.timeoutMs === undefined) return undefined;
  if (!Number.isFinite(opts.timeoutMs) || opts.timeoutMs <= 0) {
    throw new Error('workflow wait timeoutMs must be a positive number');
  }
  return Math.floor(opts.timeoutMs);
}

function hasVerificationWork(verification: WorkflowTaskVerification | undefined): boolean {
  return verification?.requiresMutation === true ||
    (verification?.requiredChangedPaths?.length ?? 0) > 0;
}

function normalizeWorkspacePath(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\.\//, '').trim();
}

function normalizeRequiredPath(value: string, ctx: KodaXToolExecutionContext): string {
  const root = ctx.gitRoot ? path.resolve(ctx.gitRoot) : undefined;
  const candidate = path.isAbsolute(value) && root
    ? path.relative(root, path.resolve(value))
    : value;
  return normalizeWorkspacePath(candidate);
}

function resolveVerificationForInput(
  input: WorkflowSpawnAgentInput,
): ResolvedVerification {
  const writeDefault: WorkflowTaskVerification | undefined = (input.readOnly ?? false) === false
    ? {
        enforcement: 'warn',
        requiresMutation: true,
        rejectPreparatoryFinalText: true,
      }
    : undefined;
  if (input.verification !== undefined) {
    const merged = {
      ...(writeDefault ?? {}),
      ...input.verification,
      enforcement: input.verification.enforcement ?? 'hard',
    };
    const requiredChangedPaths = input.verification.requiredChangedPaths;
    return {
      verification: {
        ...merged,
        ...(requiredChangedPaths !== undefined &&
          requiredChangedPaths.length > 0 &&
          merged.requiresMutation === undefined
          ? { requiresMutation: true }
          : {}),
      },
    };
  }
  return { verification: writeDefault };
}

function resolveSpawnAgentInput(
  input: WorkflowSpawnAgentInput,
  defaultChildReadOnly: boolean | undefined,
): WorkflowSpawnAgentInput {
  if (defaultChildReadOnly === true && input.readOnly === false) {
    throw new Error(
      `workflow manifest readOnly=true cannot spawn write-capable child "${input.name}"; ` +
        'set the workflow manifest readOnly=false or use child readOnly:true',
    );
  }
  const readOnly = input.readOnly ?? defaultChildReadOnly ?? false;
  return input.readOnly === readOnly ? input : { ...input, readOnly };
}

function isPreparatoryOnlyText(text: string): boolean {
  const trimmed = text.trim();
  return trimmed.length > 0 && PREPARATORY_FINAL_TEXT_RE.test(trimmed);
}

function selectWorkflowFinalText(childSummary: string, digest: string | undefined): string {
  const summary = childSummary.trim();
  const cleanDigest = digest?.trim();
  if (cleanDigest && (summary.length === 0 || isPreparatoryOnlyText(summary))) {
    return cleanDigest;
  }
  return childSummary;
}

async function runGit(args: readonly string[], cwd: string): Promise<string> {
  await assertNoGitInstallPrompt({ cwd });
  const result = await execFileAsync('git', [...args], {
    cwd,
    timeout: GIT_STATUS_TIMEOUT_MS,
    windowsHide: true,
    maxBuffer: 4 * 1024 * 1024,
  });
  return result.stdout.toString();
}

async function listGitChangedFiles(ctx: KodaXToolExecutionContext): Promise<readonly string[]> {
  const cwd = ctx.gitRoot ?? ctx.executionCwd ?? process.cwd();
  const root = (await runGit(['rev-parse', '--show-toplevel'], cwd)).trim();
  const outputs = await Promise.all([
    runGit(['diff', '--name-only', '--'], root),
    runGit(['diff', '--cached', '--name-only', '--'], root),
    runGit(['ls-files', '--others', '--exclude-standard'], root),
  ]);
  return [
    ...new Set(
      outputs
        .flatMap((output) => output.split(/\r?\n/))
        .map(normalizeWorkspacePath)
        .filter((item) => item.length > 0),
    ),
  ];
}

async function captureChangedPaths(
  ctx: KodaXToolExecutionContext,
  listChangedFiles: (ctx: KodaXToolExecutionContext) => Promise<readonly string[]>,
): Promise<ChangedPathSnapshot> {
  try {
    const paths = await listChangedFiles(ctx);
    return { paths: paths.map(normalizeWorkspacePath).filter((item) => item.length > 0) };
  } catch (error) {
    return {
      paths: [],
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

function createMutationRecorder(): MutationRecorder {
  return {
    toolNameById: new Map(),
    toolPathById: new Map(),
    succeededToolCalls: [],
    succeededPaths: [],
    readPathById: new Map(),
    succeededReadPaths: [],
  };
}

function readMutationPath(input: Record<string, unknown> | undefined): string | undefined {
  if (!input) return undefined;
  for (const key of ['path', 'file_path', 'target_path']) {
    const value = input[key];
    if (typeof value === 'string' && value.trim().length > 0) {
      return normalizeWorkspacePath(value);
    }
  }
  return undefined;
}

function wrapEventsForMutationRecording(
  original: KodaXEvents | undefined,
  recorder: MutationRecorder,
): KodaXEvents {
  return {
    ...(original ?? {}),
    onToolUseStart: (tool, meta) => {
      if (MUTATING_TOOL_NAMES.has(tool.name)) {
        recorder.toolNameById.set(tool.id, tool.name);
        const targetPath = readMutationPath(tool.input);
        if (targetPath !== undefined) {
          recorder.toolPathById.set(tool.id, targetPath);
        }
      }
      if (READING_TOOL_NAMES.has(tool.name)) {
        const targetPath = readMutationPath(tool.input);
        if (targetPath !== undefined) recorder.readPathById.set(tool.id, targetPath);
      }
      original?.onToolUseStart?.(tool, meta);
    },
    onToolResult: (result, meta) => {
      const toolName = recorder.toolNameById.get(result.id) ?? result.name;
      if (
        MUTATING_TOOL_NAMES.has(toolName) &&
        !result.content.trimStart().startsWith('[Tool Error]')
      ) {
        recorder.succeededToolCalls.push(toolName);
        const targetPath = recorder.toolPathById.get(result.id);
        if (targetPath !== undefined) {
          recorder.succeededPaths.push(targetPath);
        }
      }
      if (
        READING_TOOL_NAMES.has(toolName) &&
        !result.content.trimStart().startsWith('[Tool Error]')
      ) {
        const targetPath = recorder.readPathById.get(result.id);
        if (targetPath !== undefined) recorder.succeededReadPaths.push(targetPath);
      }
      original?.onToolResult?.(result, meta);
    },
  };
}

function uniqueItems(items: readonly string[]): readonly string[] {
  return [...new Set(items.filter((item) => item.trim().length > 0))];
}

function evaluateVerification(input: {
  readonly verification: WorkflowTaskVerification | undefined;
  readonly term: ReturnType<typeof deriveTerminal>;
  readonly before: ChangedPathSnapshot;
  readonly after: ChangedPathSnapshot;
  readonly mutationRecorder: MutationRecorder;
  readonly ctx: KodaXToolExecutionContext;
  readonly acceptToolMutationEvidence: boolean;
}): WorkflowTaskVerificationResult | undefined {
  const verification = input.verification;
  if (!verification) return undefined;

  const reasons: string[] = [];
  const beforePaths = new Set(input.before.paths.map(normalizeWorkspacePath));
  const afterPaths = uniqueItems(input.after.paths.map(normalizeWorkspacePath));
  const newlyChangedPaths = afterPaths.filter((item) => !beforePaths.has(item));
  const observedToolCalls = uniqueItems(input.mutationRecorder.succeededToolCalls);
  const toolCalls = input.acceptToolMutationEvidence ? observedToolCalls : [];
  const toolPaths = input.acceptToolMutationEvidence
    ? uniqueItems(input.mutationRecorder.succeededPaths.map(normalizeWorkspacePath))
    : [];
  const mutationEvidence = newlyChangedPaths.length > 0 || toolCalls.length > 0;
  const enforcement = verification.enforcement ?? 'hard';
  const requiredPaths = (verification.requiredChangedPaths ?? [])
    .map((item) => normalizeRequiredPath(item, input.ctx));
  const readPaths = uniqueItems(
    input.mutationRecorder.succeededReadPaths.map((item) => normalizeRequiredPath(item, input.ctx)),
  );
  const requiredReadPaths = (verification.requiredReadPaths ?? [])
    .map((item) => normalizeRequiredPath(item, input.ctx));

  if (verification.requiresMutation === true) {
    if (input.before.error !== undefined || input.after.error !== undefined) {
      reasons.push(
        `workspace mutation verification could not read changed files: ${
          input.after.error ?? input.before.error
        }`,
      );
    } else if (!mutationEvidence) {
      reasons.push(
        input.acceptToolMutationEvidence || observedToolCalls.length === 0
          ? 'expected file mutations, but no new workspace changes or successful write tools were observed'
          : 'write tools ran in an isolated worktree, but no main workspace changes were present after cleanup',
      );
    }
  }

  if (input.term.limitReached === true && !mutationEvidence) {
    reasons.push('workflow child reached its iteration limit before satisfying the task');
  }

  for (const requiredPath of requiredPaths) {
    if (!afterPaths.includes(requiredPath) && !toolPaths.includes(requiredPath)) {
      reasons.push(`required changed path was not present in workspace changes: ${requiredPath}`);
    }
  }
  for (const requiredPath of requiredReadPaths) {
    if (!readPaths.includes(requiredPath)) {
      reasons.push(`required review evidence was not read: ${requiredPath}`);
    }
  }

  const minFinalTextChars = verification.minFinalTextChars;
  if (
    minFinalTextChars !== undefined &&
    !mutationEvidence &&
    input.term.finalText.trim().length < minFinalTextChars
  ) {
    reasons.push(
      `finalText was shorter than the required ${minFinalTextChars} characters`,
    );
  }

  if (
    verification.rejectPreparatoryFinalText === true &&
    !mutationEvidence &&
    isPreparatoryOnlyText(input.term.finalText)
  ) {
    reasons.push('finalText looks preparatory instead of terminal');
  }

  return {
    ok: reasons.length === 0,
    enforcement,
    reasons,
    changedPaths: afterPaths,
    mutationToolCalls: observedToolCalls,
    mutationEvidence,
    ...(readPaths.length > 0 ? { readPaths } : {}),
  };
}

function appendVerificationFailure(
  finalText: string,
  verification: WorkflowTaskVerificationResult,
): string {
  if (verification.ok) return finalText;
  const header = verification.enforcement === 'warn'
    ? '[Workflow task completed without verification]'
    : '[Workflow task verification failed]';
  const suffix = [
    header,
    ...verification.reasons.map((reason) => `- ${reason}`),
  ].join('\n');
  return finalText.trim().length > 0 ? `${finalText}\n\n${suffix}` : suffix;
}

function limitReachedWarningVerification(): WorkflowTaskVerificationResult {
  return {
    ok: false,
    enforcement: 'warn',
    reasons: ['workflow child reached its iteration limit before satisfying the task'],
    mutationEvidence: false,
  };
}

function shouldRepairVerificationFailure(input: {
  readonly entry: WorkflowStepBinding;
  readonly term: ReturnType<typeof deriveTerminal>;
  readonly verification: WorkflowTaskVerificationResult | undefined;
}): boolean {
  return input.entry.bundle.readOnly !== true &&
    input.entry.repairAttempts < DEFAULT_VERIFICATION_REPAIR_ATTEMPTS &&
    input.term.status === 'completed' &&
    input.verification !== undefined &&
    input.verification.ok !== true &&
    input.verification.enforcement !== 'warn';
}

function buildVerificationRepairPrompt(input: {
  readonly originalPrompt: string;
  readonly previousFinalText: string;
  readonly verification: WorkflowTaskVerificationResult;
  readonly attempt: number;
}): string {
  const reasons = input.verification.reasons.map((reason) => `- ${reason}`).join('\n');
  const changedPaths = (input.verification.changedPaths ?? []).length > 0
    ? `\nWorkspace changes already present before this repair attempt:\n${
        input.verification.changedPaths?.map((item) => `- ${item}`).join('\n') ?? ''
      }`
    : '';
  return [
    input.originalPrompt,
    '',
    '[Workflow verification repair]',
    `Repair attempt ${input.attempt}/${DEFAULT_VERIFICATION_REPAIR_ATTEMPTS}.`,
    'The previous attempt did not satisfy the workflow postconditions.',
    'Do not stop at analysis, planning, or a promise to begin. Complete the required file writes in the real workspace now.',
    'Use the available file editing tools when a file change is required, then report the exact files changed.',
    '',
    'Verification failures:',
    reasons,
    changedPaths,
    '',
    'Previous terminal response:',
    input.previousFinalText.trim() || '(empty)',
  ].join('\n');
}

function buildBundle(
  childId: string,
  input: WorkflowSpawnAgentInput,
  knownTaskIds?: ReadonlySet<string>,
  actorPathByTaskId?: ReadonlyMap<string, string>,
  kodaxAuthored = false,
): KodaXChildContextBundle {
  // FEATURE_246 Phase 2: fail fast at spawn if the declared outputSchema uses a
  // keyword the subset validator can't honor — otherwise validation would be a
  // silent no-op and the author would never know.
  if (input.outputSchema !== undefined) {
    assertSupportedOutputSchema(input.outputSchema);
  }
  // FEATURE_246 (review): same fail-fast for evidenceRefs — a ref with no valid
  // prefix (an agent name instead of task_id:<id>), or a task_id:<id> that was
  // never spawned, would otherwise resolve to an "(unknown)" / "(not found)"
  // briefing fragment and silently degrade the child. Enforced on every spawn
  // (generator + inline), not just the generator smoke dry-run.
  assertValidWorkflowEvidenceRefs(input.name, input.evidenceRefs, knownTaskIds);
  return {
    id: childId,
    fanoutClass: 'evidence-scan',
    objective: input.prompt,
    ...(input.scopeSummary ? { scopeSummary: input.scopeSummary } : {}),
    readOnly: input.readOnly ?? false,
    evidenceRefs: input.evidenceRefs?.map((ref) => {
      if (!ref.startsWith('task_id:')) return ref;
      const taskId = ref.slice('task_id:'.length).trim();
      const actorPath = actorPathByTaskId?.get(taskId);
      if (!actorPath) throw new Error(`Workflow task ${taskId} has no Actor path.`);
      return `agent:${actorPath}`;
    }) ?? [],
    constraints: input.constraints ? [...input.constraints] : [],
    ...(input.modelHint ? { modelHint: input.modelHint } : {}),
    ...(input.isolation ? { isolation: input.isolation } : {}),
    ...(input.subagentType ? { specialistName: input.subagentType } : {}),
    ...(input.outputSchema !== undefined ? { outputSchema: input.outputSchema } : {}),
    ...(kodaxAuthored ? {
      workflowOutputContract: {
        kodaxAuthored: true,
        terseResult: input.terseResult === true,
      },
    } : {}),
    // Per-child effort is normalized downstream by resolveChildEffort
    // (normalizeReasoningEffortValue), so an opaque string is safe here.
    ...(input.effort ? { effort: input.effort as KodaXWireReasoningEffort } : {}),
  };
}

/** Derive workflow-level terminal status + final text from a single-bundle
 *  execution result. */
function deriveTerminal(
  result: KodaXChildExecutionResult,
  taskId: string,
): {
  status: WorkflowTaskStatus;
  snapStatus: WorkflowChildSnapshotStatus;
  finalText: string;
  digest?: string;
  digestFailed?: boolean;
  digestPending?: boolean;
  limitReached?: boolean;
  provider?: string;
  model?: string;
  structured?: unknown;
  digestTokensUsed?: number;
  digestUsage?: WorkflowTaskResult['digestUsage'];
  routeFacts?: KodaXChildRouteFacts;
} {
  if (result.cancelledChildren.includes(taskId)) {
    return { status: 'stopped', snapStatus: 'aborted', finalText: '' };
  }
  const child = result.results[0];
  const finalText = selectWorkflowFinalText(child?.summary ?? '', child?.digest);
  if (child?.status === 'completed') {
    return {
      status: 'completed',
      snapStatus: 'completed',
      finalText,
      ...(child.digest ? { digest: child.digest } : {}),
      ...(child.digestFailed ? { digestFailed: true } : {}),
      ...(child.digestPending ? { digestPending: true } : {}),
      ...(child.limitReached ? { limitReached: true } : {}),
      ...(child.provider ? { provider: child.provider } : {}),
      ...(child.model ? { model: child.model } : {}),
      ...(child.structured !== undefined ? { structured: child.structured } : {}),
      ...(child.digestTokensUsed !== undefined ? { digestTokensUsed: child.digestTokensUsed } : {}),
      ...(child.digestUsage !== undefined ? { digestUsage: child.digestUsage } : {}),
      ...(child.routeFacts ? { routeFacts: child.routeFacts } : {}),
    };
  }
  return {
    status: 'failed',
    snapStatus: 'failed',
    finalText,
    ...(child?.limitReached ? { limitReached: true } : {}),
    ...(child?.provider ? { provider: child.provider } : {}),
    ...(child?.model ? { model: child.model } : {}),
    ...(child?.digestTokensUsed !== undefined ? { digestTokensUsed: child.digestTokensUsed } : {}),
    ...(child?.digestUsage !== undefined ? { digestUsage: child.digestUsage } : {}),
    ...(child?.routeFacts ? { routeFacts: child.routeFacts } : {}),
  };
}

interface PendingChildResult {
  readonly promise: Promise<KodaXChildExecutionResult>;
  resolve(result: KodaXChildExecutionResult): void;
  reject(error: unknown): void;
}

function createPendingChildResult(): PendingChildResult {
  let resolvePromise: (result: KodaXChildExecutionResult) => void = () => {};
  let rejectPromise: (error: unknown) => void = () => {};
  const promise = new Promise<KodaXChildExecutionResult>((resolve, reject) => {
    resolvePromise = resolve;
    rejectPromise = reject;
  });
  void promise.catch(() => undefined);
  return { promise, resolve: resolvePromise, reject: rejectPromise };
}

function workflowActorTaskName(name: string, sequence: number): string {
  const normalized = name
    .normalize('NFKD')
    .replace(/[^A-Za-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
  const base = /^[A-Za-z]/.test(normalized) && !/^(?:root|workflow|external)(?:[-_]|$)/i.test(normalized)
    ? normalized
    : 'step';
  return `${base}-${sequence}`;
}

function workflowActorMetadata(input: {
  readonly workflow: WorkflowSpawnAgentInput;
  readonly executionKey?: string;
  readonly agentId?: string;
  readonly specialistName?: string;
  readonly workflowRunId?: string;
}): Readonly<Record<string, AgentMetadataValue>> {
  const workflow = input.workflow;
  return {
    readOnly: workflow.readOnly !== false,
    constraints: [...(workflow.constraints ?? [])],
    evidenceRefs: [...(workflow.evidenceRefs ?? [])],
    ...(workflow.scopeSummary ? { scope: workflow.scopeSummary } : {}),
    ...(workflow.modelHint ? { modelHint: workflow.modelHint } : {}),
    ...(workflow.isolation ? { isolation: workflow.isolation } : {}),
    ...(workflow.effort ? { effort: workflow.effort } : {}),
    ...(input.executionKey ? { executionKey: input.executionKey } : {}),
    ...(input.agentId ? { agentId: input.agentId } : {}),
    ...(input.specialistName ? { specialistName: input.specialistName } : {}),
    ...(input.workflowRunId ? { workflowRunId: input.workflowRunId } : {}),
    ...(workflow.target?.expectedConfigurationRevision
      ? { expectedConfigurationRevision: workflow.target.expectedConfigurationRevision }
      : {}),
  };
}

function actorExecutionResult(result: KodaXChildExecutionResult, taskId: string): AgentExecutionResult {
  const terminal = deriveTerminal(result, taskId);
  if (terminal.status !== 'completed' && terminal.status !== 'completed_unverified') {
    throw new Error(terminal.finalText || `Workflow Agent ${taskId} ${terminal.status}.`);
  }
  const artifacts = result.mergedArtifacts.filter(Boolean);
  return {
    output: terminal.finalText,
    ...(artifacts.length > 0 ? { artifacts } : {}),
  };
}

/**
 * Build a `WorkflowAgentBackend` over the coding child-dispatch substrate.
 */
export function createCodingWorkflowBackend(deps: CodingWorkflowBackendDeps): WorkflowAgentBackend {
  const { ctx, childOptions } = deps;
  const runChild = deps.runChild ?? executeChildAgents;
  const actorControl = ctx.actorControl;
  const actorHost = ctx.actorHost;
  if (!actorControl || !actorHost) {
    throw new Error('Workflow execution requires the Runtime-owned Actor control plane.');
  }
  const listChangedFiles = deps.listChangedFiles ?? listGitChangedFiles;
  let counter = 0;
  let actorSequence = 0;
  const genId = deps.generateId ?? (() => `wf-child-${(counter += 1)}`);

  const stepBindings = new Map<string, WorkflowStepBinding>();
  const summarySubscribers = new Set<(
    taskId: string,
    update: WorkflowTaskSummaryEventUpdate,
  ) => void>();

  const hasTaskSummaryObservers = (): boolean =>
    deps.onTaskSummary !== undefined || summarySubscribers.size > 0;

  const notifyTaskSummary = (
    taskId: string,
    update: WorkflowTaskSummaryEventUpdate,
  ): void => {
    try {
      deps.onTaskSummary?.(taskId, update);
    } catch (error) {
      emitKodaXDiagnostic({
        source: 'coding:workflow-summary',
        level: 'warn',
        message: error instanceof Error ? error.message : String(error),
      });
    }
    for (const subscriber of summarySubscribers) {
      try {
        subscriber(taskId, update);
      } catch (error) {
        emitKodaXDiagnostic({
          source: 'coding:workflow-summary',
          level: 'warn',
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }
  };

  const registerExecution = (
    taskId: string,
    bundle: KodaXChildContextBundle,
    runBundle: WorkflowStepBinding['runBundle'],
    attempt: number,
  ): { readonly key: string; readonly promise: Promise<KodaXChildExecutionResult>; cancel(): void } => {
    const key = `workflow:${deps.runId ?? 'inline'}:${taskId}:${attempt}`;
    const pending = createPendingChildResult();
    let unregister = (): void => {};
    const executor: AgentTurnExecutor = {
      async execute(execution): Promise<AgentExecutionResult> {
        try {
          const result = await runBundle(
            bundle,
            execution,
            actorHost.bindActor(execution.actor.path),
          );
          pending.resolve(result);
          return actorExecutionResult(result, taskId);
        } catch (error) {
          pending.reject(error);
          throw error;
        } finally {
          unregister();
        }
      },
    };
    unregister = actorHost.registerTurnExecutor(key, executor);
    return { key, promise: pending.promise, cancel: unregister };
  };

  const spawn = async (input: WorkflowSpawnAgentInput): Promise<WorkflowTaskHandle> => {
    let effectiveInput = resolveSpawnAgentInput(input, deps.defaultChildReadOnly);
    let kind: AgentExecutionKind = effectiveInput.subagentType ? 'constructed' : 'native';
    let specialistName = effectiveInput.subagentType;
    let specialistToolCeiling = specialistName
      ? (() => {
          const entry = resolveConstructedAgentEntry(specialistName, ctx.agentScope);
          return entry ? constructedAgentToolCeiling(entry) : undefined;
        })()
      : undefined;
    let externalControl: AgentCapabilities['control'] | undefined;
    let externalAgentId: string | undefined;
    if (effectiveInput.target && effectiveInput.subagentType) {
      throw new Error('Workflow target and subagentType are mutually exclusive.');
    }
    if (effectiveInput.target) {
      const binding = ctx.agentExecutorPlane;
      if (!binding) throw new Error('Workflow target requires a host-bound agent executor plane.');
      const localRoute = resolveCodingDispatchableAgent(
        effectiveInput.target.agentId,
        binding.context,
        ctx.agentScope,
      );
      if (localRoute) {
        if (
          effectiveInput.target.expectedConfigurationRevision !== undefined
          && effectiveInput.target.expectedConfigurationRevision
            !== localRoute.descriptor.configurationRevision
        ) {
          throw new Error('Workflow target configuration revision changed.');
        }
        const { target: ignoredTarget, ...untargetedInput } = effectiveInput;
        void ignoredTarget;
        effectiveInput = {
          ...untargetedInput,
          ...(localRoute.subagentType ? { subagentType: localRoute.subagentType } : {}),
        };
        kind = localRoute.kind;
        specialistName = localRoute.subagentType;
        specialistToolCeiling = localRoute.toolCeiling;
      } else {
        if (effectiveInput.modelHint !== undefined || effectiveInput.effort !== undefined) {
          throw new Error(
            'External Workflow targets cannot combine local modelHint/effort routing selectors.',
          );
        }
        if (effectiveInput.verification?.requiresMutation === true) {
          throw new Error('External Workflow targets cannot directly satisfy workspace mutation verification.');
        }
        const described = await binding.plane.describe(
          effectiveInput.target.agentId,
          { ...binding.context, readOnly: effectiveInput.readOnly },
          listCodingDispatchableAgents(binding.context, ctx.agentScope),
        );
        if (!described || described.descriptor.origin !== 'external') {
          throw new Error(`Workflow target is not dispatchable: ${effectiveInput.target.agentId}`);
        }
        if (
          effectiveInput.target.expectedConfigurationRevision !== undefined
          && effectiveInput.target.expectedConfigurationRevision
            !== described.descriptor.configurationRevision
        ) throw new Error('Workflow target configuration revision changed.');
        const capabilities = described.descriptor.capabilities;
        kind = 'external';
        externalAgentId = effectiveInput.target.agentId;
        externalControl = {
          followup: capabilities.inputRequired !== 'unsupported',
          interrupt: capabilities.cancellation !== 'unsupported',
          streaming: capabilities.streaming !== 'unsupported',
          artifacts: capabilities.artifacts !== 'unsupported',
        };
      }
    }
    const childId = genId();
    // Step bindings hold every Agent spawned earlier in this run, so this is
    // exactly the set a
    // `task_id:` evidence ref may legitimately point back to.
    const bundle = buildBundle(
      childId,
      effectiveInput,
      new Set(stepBindings.keys()),
      new Map([...stepBindings].map(([taskId, binding]) => [taskId, binding.actorPath])),
      deps.kodaxAuthored === true,
    );
    const resolvedVerification = resolveVerificationForInput(effectiveInput);
    const verification = resolvedVerification.verification;
    const mutationRecorder = createMutationRecorder();
    const acceptToolMutationEvidence = effectiveInput.isolation !== 'worktree';
    const changedPathBaseline = hasVerificationWork(verification)
      ? captureChangedPaths(ctx, listChangedFiles)
      : Promise.resolve({ paths: [] });
    const runBundle: WorkflowStepBinding['runBundle'] = async (
      runBundleInput,
      execution,
      childActorControl,
    ) => {
    const perChild: ChildExecutorOptions = {
      ...childOptions,
      parentOptions: {
        ...childOptions.parentOptions,
        events: wrapEventsForMutationRecording(
          childOptions.parentOptions.events,
          mutationRecorder,
        ),
      },
      maxParallel: 1,
      // FEATURE_217 — every child launched through the workflow backend gets the
      // self-distill digest. This is the single workflow boundary, so it marks
      // workflow children without overloading `parentHarness` (which stays
      // 'tool-dispatch' so write children are not dropped by validateWriteBundles).
      workflowChild: true,
      ...(deps.runId !== undefined
        ? {
            workflowCorrelation: {
              workflowRunId: deps.runId,
              childAgentId: childId,
              itemId: `agent:${childId}`,
            },
          }
        : {}),
      childActivityName: effectiveInput.name,
      // NOTE: in a real run this is effectively always 'async' — the workflow
      // runtime self-subscribes to task-summary updates for `agent_summary_updated`
      // telemetry (runtime.ts), so `hasTaskSummaryObservers()` is true even with
      // no host UI attached. The `'blocking'` fallback here is reached only by a
      // test backend that omits a summary subscriber; worktree children take the
      // synchronous digest path via a SEPARATE gate (shouldRunWorkflowDigestAsync's
      // `isolation !== 'worktree'`), not this ternary. Do not read this line as
      // "headless runs compute the digest synchronously" — they do not.
      workflowDigestMode: hasTaskSummaryObservers() ? 'async' : 'blocking',
      ...(hasTaskSummaryObservers()
        ? {
            onWorkflowChildDigest: (update) => {
              notifyTaskSummary(update.childId, {
                ...(update.digest ? { summary: update.digest } : {}),
                summaryKind: update.digest ? 'digest' : 'digest-failed',
                ...(update.totalTokensUsed > 0
                  ? { usage: update.usage ?? { totalTokens: update.totalTokensUsed } }
                  : {}),
              });
            },
          }
        : {}),
      abortSignal: execution.signal,
      // Workflow steps are protocol leaves by default. The Actor controller
      // retains lifecycle authority without granting recursive model tools.
      // The admitted capability snapshot still constrains the leaf's actual
      // tool/provider route even though no Actor control surface is exposed.
      actorControl: undefined,
      actorHost: undefined,
      actorCapabilities: execution.actor.capabilities,
      contextAgentId: execution.actor.path,
      ...(execution.actor.parentPath !== undefined
        ? { contextParentAgentId: execution.actor.parentPath }
        : {}),
    };

      await changedPathBaseline;
      void childActorControl;
      return runChild([runBundleInput], ctx, perChild);
    };

    const registered = kind === 'external'
      ? undefined
      : registerExecution(childId, bundle, runBundle, 1);
    actorSequence += 1;
    let turn;
    try {
      turn = await actorControl.spawn({
        taskName: workflowActorTaskName(effectiveInput.name, actorSequence),
        objective: effectiveInput.prompt,
        kind,
        capabilities: {
          filesystem: effectiveInput.readOnly !== false ? 'read' : 'write',
          canAskUser: false,
          ...(specialistToolCeiling !== undefined
            ? {
                tools: intersectWorkflowToolCeilings(
                  specialistToolCeiling,
                  actorControl.get(actorControl.callerPath).actor.capabilities.tools,
                ),
              }
            : {}),
          ...(externalControl ? { control: externalControl } : {}),
        },
        metadata: workflowActorMetadata({
          workflow: effectiveInput,
          ...(registered ? { executionKey: registered.key } : {}),
          ...(externalAgentId ? { agentId: externalAgentId } : {}),
          ...(specialistName ? { specialistName } : {}),
          ...(deps.runId ? { workflowRunId: deps.runId } : {}),
        }),
      });
    } catch (error) {
      registered?.cancel();
      throw error;
    }
    stepBindings.set(childId, {
      name: effectiveInput.name,
      input: effectiveInput,
      bundle,
      actorPath: turn.actorPath,
      turnId: turn.turnId,
      ...(registered ? { promise: registered.promise } : {}),
      runBundle,
      external: kind === 'external',
      verification,
      changedPathBaseline,
      mutationRecorder,
      acceptToolMutationEvidence,
      repairAttempts: 0,
    });
    return { taskId: childId, name: effectiveInput.name };
  };

  const waitForActorTurn = async (
    entry: WorkflowStepBinding,
    timeoutMs: number | undefined,
    timeoutLabelMs: number | undefined = timeoutMs,
  ): Promise<void> => {
    const isTurnTerminal = (): boolean => {
      const state = actorControl.output(entry.actorPath, entry.turnId).state;
      return state === 'completed' || state === 'failed' || state === 'interrupted';
    };
    const isTerminalEvent = (event: AgentEvent): boolean => (
      event.turnId === entry.turnId
      && (event.kind === 'turn_completed'
        || event.kind === 'turn_failed'
        || event.kind === 'turn_interrupted')
    );
    const interruptOrAcceptTerminal = async (): Promise<boolean> => {
      if (isTurnTerminal()) return false;
      try {
        await actorControl.interrupt(entry.actorPath, 'workflow wait timeout');
        return true;
      } catch (error) {
        if (isTurnTerminal()) return false;
        throw error;
      }
    };
    const deadline = timeoutMs === undefined ? undefined : Date.now() + timeoutMs;
    let cursor = 0;
    for (;;) {
      if (isTurnTerminal()) return;
      const events = actorControl.eventSnapshot(cursor);
      const terminal = events.find(isTerminalEvent);
      if (terminal) return;
      cursor = events.at(-1)?.sequence ?? cursor;
      const remaining = deadline === undefined ? undefined : deadline - Date.now();
      if (remaining !== undefined && remaining <= 0) {
        if (await interruptOrAcceptTerminal()) {
          throw new Error(`workflow task ${entry.name} timed out after ${timeoutLabelMs ?? timeoutMs}ms`);
        }
        return;
      }
      const event = await actorControl.wait(cursor, remaining);
      // AgentActorController.wait() has its own 30s polling window when
      // timeoutMs is undefined. An empty poll is not a Workflow timeout.
      if (!event) continue;
      if (isTerminalEvent(event)) return;
      cursor = event.sequence;
    }
  };

  const wait = async (
    taskId: string,
    opts?: WorkflowWaitOptions,
  ): Promise<WorkflowTaskResult> => {
    const entry = stepBindings.get(taskId);
    if (!entry) throw new Error(`unknown workflow task: ${taskId}`);
    const totalWaitTimeoutMs = normalizeWaitTimeoutMs(opts);
    const waitStartedAt = Date.now();
    const waitForAttempt = async (
      promise: Promise<KodaXChildExecutionResult> | undefined,
    ): Promise<KodaXChildExecutionResult> => {
      const elapsedMs = Date.now() - waitStartedAt;
      const remainingMs = totalWaitTimeoutMs === undefined
        ? undefined
        : Math.max(0, totalWaitTimeoutMs - elapsedMs);
      await waitForActorTurn(entry, remainingMs, totalWaitTimeoutMs);
      if (!promise) throw new Error(`workflow task ${taskId} has no local execution result`);
      return promise;
    };
    if (entry.external) {
      await waitForActorTurn(entry, totalWaitTimeoutMs);
      const output = actorControl.output(entry.actorPath, entry.turnId);
      return {
        taskId,
        name: entry.name,
        status: output.state === 'completed'
          ? 'completed'
          : output.state === 'interrupted' ? 'stopped' : 'failed',
        finalText: output.output ?? output.error ?? '',
        ...(output.structured === undefined ? {} : { structured: output.structured }),
        ...(output.artifacts.length === 0 ? {} : { artifacts: output.artifacts }),
      };
    }
    let result = await waitForAttempt(entry.promise);
    let totalTokensUsed = result.totalTokensUsed;
    let term = deriveTerminal(result, taskId);
    const initialRouteFacts = term.routeFacts;
    let totalInputTokens = term.routeFacts?.inputTokens ?? 0;
    let totalOutputTokens = term.routeFacts?.outputTokens ?? 0;
    let totalCacheReadTokens = term.routeFacts?.cacheReadTokens ?? 0;
    let totalIterations = term.routeFacts?.iterations ?? 0;
    let totalDurationMs = term.routeFacts?.durationMs ?? 0;
    let fallbackReason = term.routeFacts?.fallbackReason;
    let digestTokensUsed = term.digestTokensUsed ?? 0;
    let digestUsage = term.digestUsage;
    let verification = entry.verification
      ? evaluateVerification({
          verification: entry.verification,
          term,
          before: await entry.changedPathBaseline,
          after: hasVerificationWork(entry.verification)
            ? await captureChangedPaths(ctx, listChangedFiles)
            : { paths: [] },
          mutationRecorder: entry.mutationRecorder,
          ctx,
          acceptToolMutationEvidence: entry.acceptToolMutationEvidence,
        })
      : undefined;
    if (term.limitReached === true && verification === undefined && term.status === 'completed') {
      verification = limitReachedWarningVerification();
      term = {
        ...term,
        status: 'completed_unverified',
        snapStatus: 'completed',
        finalText: appendVerificationFailure(term.finalText, verification),
      };
    }
    while (shouldRepairVerificationFailure({ entry, term, verification })) {
      entry.repairAttempts += 1;
      const repairPrompt = buildVerificationRepairPrompt({
        originalPrompt: entry.input.prompt,
        previousFinalText: term.finalText,
        verification: verification!,
        attempt: entry.repairAttempts,
      });
      const repairBundle = buildBundle(taskId, {
        ...entry.input,
        prompt: repairPrompt,
      }, new Set(stepBindings.keys()), new Map(
        [...stepBindings].map(([knownTaskId, binding]) => [knownTaskId, binding.actorPath]),
      ), deps.kodaxAuthored === true);
      const registered = registerExecution(
        taskId,
        repairBundle,
        entry.runBundle,
        entry.repairAttempts + 1,
      );
      entry.promise = registered.promise;
      try {
        const followup = await actorControl.followup(
          entry.actorPath,
          repairPrompt,
          { executionKey: registered.key },
        );
        entry.turnId = followup.turn.turnId;
      } catch (error) {
        registered.cancel();
        throw error;
      }
      result = await waitForAttempt(entry.promise);
      totalTokensUsed += result.totalTokensUsed;
      term = deriveTerminal(result, taskId);
      totalInputTokens += term.routeFacts?.inputTokens ?? 0;
      totalOutputTokens += term.routeFacts?.outputTokens ?? 0;
      totalCacheReadTokens += term.routeFacts?.cacheReadTokens ?? 0;
      totalIterations += term.routeFacts?.iterations ?? 0;
      totalDurationMs += term.routeFacts?.durationMs ?? 0;
      fallbackReason ??= term.routeFacts?.fallbackReason;
      digestTokensUsed += term.digestTokensUsed ?? 0;
      if (term.digestUsage) {
        digestUsage = {
          inputTokens: (digestUsage?.inputTokens ?? 0) + (term.digestUsage.inputTokens ?? 0),
          outputTokens: (digestUsage?.outputTokens ?? 0) + (term.digestUsage.outputTokens ?? 0),
          totalTokens: (digestUsage?.totalTokens ?? 0) + (term.digestUsage.totalTokens ?? 0),
          cacheReadTokens: (digestUsage?.cacheReadTokens ?? 0) + (term.digestUsage.cacheReadTokens ?? 0),
        };
      }
      verification = entry.verification
        ? evaluateVerification({
            verification: entry.verification,
            term,
            before: await entry.changedPathBaseline,
            after: hasVerificationWork(entry.verification)
              ? await captureChangedPaths(ctx, listChangedFiles)
              : { paths: [] },
            mutationRecorder: entry.mutationRecorder,
            ctx,
            acceptToolMutationEvidence: entry.acceptToolMutationEvidence,
          })
        : undefined;
      if (term.limitReached === true && verification === undefined && term.status === 'completed') {
        verification = limitReachedWarningVerification();
        term = {
          ...term,
          status: 'completed_unverified',
          snapStatus: 'completed',
          finalText: appendVerificationFailure(term.finalText, verification),
        };
      }
    }
    if (verification !== undefined && !verification.ok && term.status === 'completed') {
      const warnOnly = verification.enforcement === 'warn';
      term = {
        ...term,
        status: warnOnly ? 'completed_unverified' : 'failed',
        snapStatus: warnOnly ? 'completed' : 'failed',
        finalText: appendVerificationFailure(term.finalText, verification),
      };
    }
    return {
      taskId,
      name: entry.name,
      status: term.status,
      finalText: term.finalText,
      ...(term.digest ? { digest: term.digest } : {}),
      ...(term.digestFailed ? { digestFailed: true } : {}),
      ...(term.digestPending ? { digestPending: true } : {}),
      ...(verification !== undefined ? { verification } : {}),
      ...(term.limitReached ? { limitReached: true } : {}),
      ...(term.provider ? { provider: term.provider } : {}),
      ...(term.model ? { model: term.model } : {}),
      ...(term.structured !== undefined ? { structured: term.structured } : {}),
      ...(result.mergedArtifacts.length > 0 ? { artifacts: result.mergedArtifacts.filter(Boolean) } : {}),
      ...(digestTokensUsed > 0 ? { digestUsage: digestUsage ?? { totalTokens: digestTokensUsed } } : {}),
      ...(term.routeFacts ? {
        requestedTier: initialRouteFacts?.requestedTier ?? term.routeFacts.requestedTier,
        tierOutcome: term.routeFacts.tierOutcome,
        providerSource: initialRouteFacts?.providerSource ?? term.routeFacts.providerSource,
        ...((initialRouteFacts?.modelSource ?? term.routeFacts.modelSource)
          ? { modelSource: initialRouteFacts?.modelSource ?? term.routeFacts.modelSource }
          : {}),
        ...((initialRouteFacts?.initialProvider ?? term.routeFacts.initialProvider)
          ? { initialProvider: initialRouteFacts?.initialProvider ?? term.routeFacts.initialProvider }
          : {}),
        ...((initialRouteFacts?.initialModel ?? term.routeFacts.initialModel)
          ? { initialModel: initialRouteFacts?.initialModel ?? term.routeFacts.initialModel }
          : {}),
        ...(term.routeFacts.finalProvider ? { finalProvider: term.routeFacts.finalProvider } : {}),
        ...(term.routeFacts.finalModel ? { finalModel: term.routeFacts.finalModel } : {}),
        ...(fallbackReason ? { fallbackReason } : {}),
        ...(term.routeFacts.resolvedEffort ? { resolvedEffort: term.routeFacts.resolvedEffort } : {}),
        ...(totalIterations > 0 ? { iterations: totalIterations } : {}),
        ...(totalDurationMs > 0 ? { durationMs: totalDurationMs } : {}),
      } : {}),
      usage: {
        totalTokens: totalTokensUsed,
        ...(totalInputTokens > 0 ? { inputTokens: totalInputTokens } : {}),
        ...(totalOutputTokens > 0 ? { outputTokens: totalOutputTokens } : {}),
        ...(totalCacheReadTokens > 0 ? { cacheReadTokens: totalCacheReadTokens } : {}),
      },
    };
  };

  const output = async (taskId: string): Promise<WorkflowTaskSnapshot> => {
    // Unknown protocol step ids fail loudly; known steps project Actor state.
    const entry = stepBindings.get(taskId);
    if (!entry) throw new Error(`unknown workflow task: ${taskId}`);
    const actor = actorControl.get(entry.actorPath).actor;
    if (actor.currentTurnId === entry.turnId) {
      return { taskId, name: entry.name, status: 'running' };
    }
    const result = actorControl.output(entry.actorPath, entry.turnId);
    const status: WorkflowTaskStatus = result.state === 'completed'
      ? 'completed'
      : result.state === 'interrupted' ? 'stopped' : 'failed';
    const lastText = result.output ?? result.error;
    return lastText === undefined
      ? { taskId, name: entry.name, status }
      : { taskId, name: entry.name, status, lastText };
  };

  const send = async (taskId: string, content: string): Promise<void> => {
    // FEATURE_246 (review A2): fail loudly on an unknown target rather than
    // silently dropping the message (the smoke api's send asserts the same).
    const entry = stepBindings.get(taskId);
    if (!entry) throw new Error(`unknown workflow task: ${taskId}`);
    await actorControl.send(entry.actorPath, content);
  };

  const stop = async (taskId: string, reason: string): Promise<void> => {
    // FEATURE_246 (review A2): fail loudly on an unknown target rather than a
    // silent no-op (optional chaining would otherwise swallow it).
    const entry = stepBindings.get(taskId);
    if (!entry) throw new Error(`unknown workflow task: ${taskId}`);
    await actorControl.interrupt(entry.actorPath, reason);
  };

  // NOTE: no `synthesize` here — `wf.synthesize` runs as a gated agent in
  // the runtime (through spawn/wait) so it counts toward maxAgents /
  // concurrency / budget and emits run-graph events.
  return {
    spawn,
    waitForAgentCapacity: (signal) => actorHost.waitForAgentCapacity(signal),
    wait,
    output,
    send,
    stop,
    subscribeTaskSummaryUpdates: (listener) => {
      summarySubscribers.add(listener);
      return () => {
        summarySubscribers.delete(listener);
      };
    },
  };
}
