/**
 * Default keyboard shortcuts.
 */

import type { ShortcutDefinition } from './types.js';

export const DEFAULT_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: 'interrupt',
    name: 'Interrupt',
    description: 'Interrupt the current streaming response',
    defaultBindings: [{ key: 'c', ctrl: true }],
    context: 'global',
    priority: 200,
    category: 'global',
    configurable: false,
  },
  {
    id: 'showHelp',
    name: 'Toggle Help',
    description: 'Show or hide shortcut help when the input is empty',
    defaultBindings: [{ key: '?' }],
    context: 'global',
    priority: 150,
    category: 'global',
    configurable: true,
  },
  {
    id: 'toggleThinking',
    name: 'Cycle Reasoning',
    description: 'Cycle reasoning mode: off, auto, quick, balanced, deep',
    defaultBindings: [{ key: 't', ctrl: true }],
    context: 'global',
    priority: 150,
    category: 'mode',
    configurable: true,
  },
  {
    id: 'togglePermissionMode',
    name: 'Cycle Permissions',
    description: 'Cycle permission mode: plan, accept-edits, auto-in-project',
    defaultBindings: [
      { key: 'o', ctrl: true },
      { key: 'tab', shift: true },
    ],
    context: 'global',
    priority: 150,
    category: 'mode',
    configurable: true,
  },
  {
    id: 'toggleAgentMode',
    name: 'Toggle Agent Mode',
    description: 'Switch between AMA and SA',
    defaultBindings: [{ key: 'm', meta: true }],
    context: 'global',
    priority: 150,
    category: 'mode',
    configurable: true,
  },
  {
    id: 'toggleParallelMode',
    name: 'Toggle Parallel',
    description: 'Toggle between parallel and sequential tool execution',
    defaultBindings: [{ key: 'p', ctrl: true }],
    context: 'global',
    priority: 150,
    category: 'mode',
    configurable: true,
  },
  {
    id: 'submitInput',
    name: 'Submit Input',
    description: 'Submit the current input',
    defaultBindings: [{ key: 'enter' }],
    context: 'input',
    priority: 50,
    category: 'global',
    configurable: false,
  },
  {
    id: 'acceptCompletion',
    name: 'Accept Completion',
    description: 'Accept the current autocomplete suggestion',
    defaultBindings: [{ key: 'tab' }],
    context: 'input',
    priority: 60,
    category: 'editing',
    configurable: true,
  },
  {
    id: 'cancelInput',
    name: 'Cancel Input',
    description: 'Cancel or clear the current input',
    defaultBindings: [{ key: 'escape' }],
    context: 'input',
    priority: 70,
    category: 'editing',
    configurable: true,
  },
  {
    id: 'newline',
    name: 'Insert Newline',
    description: 'Insert a newline in the current input',
    defaultBindings: [
      { key: 'enter', shift: true },
      { key: 'j', ctrl: true },
    ],
    context: 'input',
    priority: 40,
    category: 'editing',
    configurable: true,
  },
  {
    id: 'historyUp',
    name: 'History Up',
    description: 'Browse previous input history',
    defaultBindings: [{ key: 'up' }],
    context: 'input',
    priority: 30,
    category: 'navigation',
    configurable: true,
  },
  {
    id: 'historyDown',
    name: 'History Down',
    description: 'Browse next input history',
    defaultBindings: [{ key: 'down' }],
    context: 'input',
    priority: 30,
    category: 'navigation',
    configurable: true,
  },
  {
    id: 'moveLeft',
    name: 'Move Left',
    description: 'Move the cursor left',
    defaultBindings: [{ key: 'left' }],
    context: 'input',
    priority: 20,
    category: 'navigation',
    configurable: false,
  },
  {
    id: 'moveRight',
    name: 'Move Right',
    description: 'Move the cursor right',
    defaultBindings: [{ key: 'right' }],
    context: 'input',
    priority: 20,
    category: 'navigation',
    configurable: false,
  },
  {
    id: 'moveToStart',
    name: 'Move To Start',
    description: 'Move the cursor to the start of the line',
    defaultBindings: [{ key: 'a', ctrl: true }],
    context: 'input',
    priority: 25,
    category: 'navigation',
    configurable: true,
  },
  {
    id: 'moveToEnd',
    name: 'Move To End',
    description: 'Move the cursor to the end of the line',
    defaultBindings: [{ key: 'e', ctrl: true }],
    context: 'input',
    priority: 25,
    category: 'navigation',
    configurable: true,
  },
  {
    id: 'moveLineUp',
    name: 'Move Line Up',
    description: 'Move to the previous visual line in multiline input',
    defaultBindings: [{ key: 'up', ctrl: true }],
    context: 'input',
    priority: 20,
    category: 'navigation',
    configurable: true,
  },
  {
    id: 'moveLineDown',
    name: 'Move Line Down',
    description: 'Move to the next visual line in multiline input',
    defaultBindings: [{ key: 'down', ctrl: true }],
    context: 'input',
    priority: 20,
    category: 'navigation',
    configurable: true,
  },
  {
    id: 'backspace',
    name: 'Backspace',
    description: 'Delete the previous character',
    defaultBindings: [{ key: 'backspace' }],
    context: 'input',
    priority: 10,
    category: 'editing',
    configurable: false,
  },
  {
    id: 'delete',
    name: 'Delete',
    description: 'Delete the next character',
    defaultBindings: [{ key: 'delete' }],
    context: 'input',
    priority: 10,
    category: 'editing',
    configurable: false,
  },
];

export function getShortcutsByContext(
  context: ShortcutDefinition['context'],
): ShortcutDefinition[] {
  return DEFAULT_SHORTCUTS.filter(
    (shortcut) => shortcut.context === context || shortcut.context === 'global',
  );
}

export function getShortcutsByCategory(
  category: ShortcutDefinition['category'],
): ShortcutDefinition[] {
  return DEFAULT_SHORTCUTS.filter((shortcut) => shortcut.category === category);
}

export function getConfigurableShortcuts(): ShortcutDefinition[] {
  return DEFAULT_SHORTCUTS.filter((shortcut) => shortcut.configurable !== false);
}
