/**
 * FEATURE_090 (v0.7.32) — `activate()` self-modify branch integration.
 *
 * Covers the new force-ask-user path layered on top of FEATURE_088's
 * activate flow. The regular first-time-staging activation continues
 * to be exercised by `runtime.test.ts` / `runtime-agent.test.ts`;
 * this file focuses on the FEATURE_090 additions:
 *
 *   - Self-modify detection (sourceAgent === name + active prev)
 *   - LLM diff summary (graceful fallback on no client)
 *   - Force-ask-user replaces the regular policy gate
 *   - Budget consume + audit entries
 *   - The non-self-modify path is unaffected when sourceAgent points
 *     at a different agent (cross-agent generation)
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import os from 'os';
import path from 'path';
import fs from 'fs/promises';

import { _resetInvariantRegistry } from '@kodax/core';

import { registerCodingInvariants } from '../agent-runtime/invariants/index.js';

import {
  configureRuntime,
  activate,
  drainPendingSwaps,
  hasPendingSwap,
  resolveConstructedAgent,
  _resetRuntimeForTesting,
  type AgentArtifact,
  type SelfModifyAskUser,
  readAuditEntries,
  readBudget,
  DEFAULT_SELF_MODIFY_BUDGET,
  remainingSelfModifyBudget,
} from './index.js';
import { consumeBudget } from './budget.js';

let tmpRoot: string;

beforeEach(async () => {
  tmpRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'kodax-self-modify-activate-'));
  _resetInvariantRegistry();
  registerCodingInvariants();
});

afterEach(async () => {
  _resetRuntimeForTesting();
  _resetInvariantRegistry();
  await fs.rm(tmpRoot, { recursive: true, force: true });
});

/** Persist an artifact directly (skips stage()/test() so the test
 *  isolates `activate()` behaviour). */
async function persistArtifactDirect(artifact: AgentArtifact): Promise<void> {
  const dir = path.join(tmpRoot, '.kodax', 'constructed', 'agents', artifact.name);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(
    path.join(dir, `${artifact.version}.json`),
    JSON.stringify(artifact, null, 2),
    'utf8',
  );
}

function buildAgent(overrides: Partial<AgentArtifact> = {}): AgentArtifact {
  return {
    kind: 'agent',
    name: overrides.name ?? 'alpha',
    version: overrides.version ?? '1.0.0',
    status: overrides.status ?? 'active',
    createdAt: overrides.createdAt ?? Date.now(),
    sourceAgent: overrides.sourceAgent,
    activatedAt: overrides.activatedAt,
    contentHash: overrides.contentHash,
    testedAt: overrides.testedAt ?? Date.now(),
    content: overrides.content ?? { instructions: 'You are alpha.' },
  } as AgentArtifact;
}

describe('activate() — self-modify detection', () => {
  it('does NOT take the self-modify path when sourceAgent differs from name', async () => {
    // alpha is active. beta was generated by alpha (sourceAgent='alpha')
    // and is being activated for the first time. This is FEATURE_089
    // cross-agent generation, NOT self-modify.
    const ask: SelfModifyAskUser = vi.fn(async (): Promise<'approve' | 'reject'> => 'approve');
    const policy = vi.fn(async () => 'approve' as const);
    configureRuntime({
      cwd: tmpRoot,
      policy,
      selfModifyAskUser: ask,
    });

    await persistArtifactDirect(buildAgent({ name: 'alpha', version: '1.0.0', status: 'active' }));
    await persistArtifactDirect(
      buildAgent({
        name: 'beta',
        version: '0.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
      }),
    );

    await activate({
      artifact: buildAgent({
        name: 'beta',
        version: '0.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
      }),
      stagedAt: Date.now(),
    });

    // Regular policy gate ran; self-modify ask did NOT.
    expect(policy).toHaveBeenCalledOnce();
    expect(ask).not.toHaveBeenCalled();
  });

  it('does NOT take the self-modify path on first-time staging (no prev active)', async () => {
    const ask: SelfModifyAskUser = vi.fn(async (): Promise<'approve' | 'reject'> => 'approve');
    const policy = vi.fn(async () => 'approve' as const);
    configureRuntime({
      cwd: tmpRoot,
      policy,
      selfModifyAskUser: ask,
    });

    // sourceAgent === name but no prior active version exists — treat
    // as first-time staging (FEATURE_089 path).
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.0.0',
        status: 'staged',
        sourceAgent: 'alpha',
      }),
    );

    await activate({
      artifact: buildAgent({
        name: 'alpha',
        version: '1.0.0',
        status: 'staged',
        sourceAgent: 'alpha',
      }),
      stagedAt: Date.now(),
    });

    expect(policy).toHaveBeenCalledOnce();
    expect(ask).not.toHaveBeenCalled();
  });
});

describe('activate() — self-modify approve path', () => {
  beforeEach(async () => {
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.0.0',
        status: 'active',
        content: { instructions: 'You are alpha.' },
      }),
    );
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
    );
  });

  it('runs LLM summary, calls ask-user, consumes budget, writes activated audit entry', async () => {
    const llmReviewer = vi.fn(async () =>
      JSON.stringify({
        summary: 'Tightened wording.',
        severity: 'minor',
        flaggedConcerns: [],
      }),
    );
    const ask: SelfModifyAskUser = vi.fn(
      async (input): Promise<'approve' | 'reject'> => {
        // Sanity-check that the ask gets the prev/next contents and the LLM summary.
        expect(input.agentName).toBe('alpha');
        expect(input.fromVersion).toBe('1.0.0');
        expect(input.toVersion).toBe('1.1.0');
        expect(input.prevContent.instructions).toBe('You are alpha.');
        expect(input.nextContent.instructions).toBe('You are alpha. Be thorough.');
        expect(input.llmSummary.severity).toBe('minor');
        expect(input.budgetRemaining).toBe(DEFAULT_SELF_MODIFY_BUDGET);
        return 'approve';
      },
    );
    const policy = vi.fn(async () => 'reject' as const);
    configureRuntime({
      cwd: tmpRoot,
      policy,
      llmReviewer,
      selfModifyAskUser: ask,
    });

    await activate({
      artifact: buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
      stagedAt: Date.now(),
    });

    expect(llmReviewer).toHaveBeenCalledOnce();
    expect(ask).toHaveBeenCalledOnce();
    // Regular policy gate is BYPASSED on the self-modify path.
    expect(policy).not.toHaveBeenCalled();

    // Persisted manifest is now active.
    const persisted = JSON.parse(
      await fs.readFile(
        path.join(tmpRoot, '.kodax', 'constructed', 'agents', 'alpha', '1.1.0.json'),
        'utf8',
      ),
    );
    expect(persisted.status).toBe('active');
    expect(persisted.contentHash).toBeTypeOf('string');

    // Budget consumed.
    const budget = await readBudget('alpha', { cwd: tmpRoot });
    expect(budget.count).toBe(1);

    // Audit entry recorded with full payload.
    const audit = await readAuditEntries({ cwd: tmpRoot, agentName: 'alpha' });
    expect(audit).toHaveLength(1);
    expect(audit[0]!.event).toBe('self_modify_activated');
    expect(audit[0]!.fromVersion).toBe('1.0.0');
    expect(audit[0]!.toVersion).toBe('1.1.0');
    expect(audit[0]!.severity).toBe('minor');
    expect(audit[0]!.policyVerdict).toBe('force-ask-user');
    expect(audit[0]!.budgetRemaining).toBe(DEFAULT_SELF_MODIFY_BUDGET - 1);
  });

  it('falls back to the unavailable-summary record when no LLM reviewer is configured', async () => {
    const ask: SelfModifyAskUser = vi.fn(
      async (input): Promise<'approve' | 'reject'> => {
        expect(input.llmSummary.severity).toBe('major');
        expect(input.llmSummary.summary).toMatch(/No LLM reviewer/);
        return 'approve';
      },
    );
    configureRuntime({
      cwd: tmpRoot,
      policy: async () => 'reject',
      selfModifyAskUser: ask,
    });

    await activate({
      artifact: buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
      stagedAt: Date.now(),
    });

    expect(ask).toHaveBeenCalledOnce();
    const audit = await readAuditEntries({ cwd: tmpRoot, agentName: 'alpha' });
    expect(audit[0]!.severity).toBe('major');
  });
});

describe('activate() — self-modify reject path', () => {
  beforeEach(async () => {
    await persistArtifactDirect(
      buildAgent({ name: 'alpha', version: '1.0.0', status: 'active' }),
    );
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
    );
  });

  it('user reject throws, does NOT consume budget, audits self_modify_rejected', async () => {
    const ask: SelfModifyAskUser = vi.fn(async (): Promise<'approve' | 'reject'> => 'reject');
    configureRuntime({
      cwd: tmpRoot,
      policy: async () => 'reject',
      selfModifyAskUser: ask,
    });

    await expect(
      activate({
        artifact: buildAgent({
          name: 'alpha',
          version: '1.1.0',
          status: 'staged',
          sourceAgent: 'alpha',
          content: { instructions: 'You are alpha. Be thorough.' },
        }),
        stagedAt: Date.now(),
      }),
    ).rejects.toThrow(/User rejected self-modify of 'alpha@1.1.0'/);

    expect(ask).toHaveBeenCalledOnce();

    // Manifest 1.1.0 stays staged on disk (status not flipped to active).
    const persisted = JSON.parse(
      await fs.readFile(
        path.join(tmpRoot, '.kodax', 'constructed', 'agents', 'alpha', '1.1.0.json'),
        'utf8',
      ),
    );
    expect(persisted.status).toBe('staged');

    // Budget NOT consumed.
    const budget = await readBudget('alpha', { cwd: tmpRoot });
    expect(budget.count).toBe(0);
    expect(remainingSelfModifyBudget(budget)).toBe(DEFAULT_SELF_MODIFY_BUDGET);

    // Audit recorded with policyVerdict='reject'.
    const audit = await readAuditEntries({ cwd: tmpRoot, agentName: 'alpha' });
    expect(audit).toHaveLength(1);
    expect(audit[0]!.event).toBe('self_modify_rejected');
    expect(audit[0]!.policyVerdict).toBe('reject');
    expect(audit[0]!.rejectRule).toBe('user-rejected');
  });

  it('hard-fails when no selfModifyAskUser callback is configured', async () => {
    configureRuntime({
      cwd: tmpRoot,
      policy: async () => 'approve',
      selfModifyAskUser: undefined,
    });

    await expect(
      activate({
        artifact: buildAgent({
          name: 'alpha',
          version: '1.1.0',
          status: 'staged',
          sourceAgent: 'alpha',
          content: { instructions: 'You are alpha. Be thorough.' },
        }),
        stagedAt: Date.now(),
      }),
    ).rejects.toThrow(/requires an interactive surface that wires `selfModifyAskUser`/);
  });
});

describe('activate() — self-modify deferred resolver swap', () => {
  beforeEach(async () => {
    // Bootstrap: register the prior version through activate() so the
    // resolver's AGENT_REGISTRY actually holds it. We can't just persist
    // the file — the resolver only learns about an agent when it is
    // activated (resp. rehydrated at startup).
    configureRuntime({
      cwd: tmpRoot,
      policy: async () => 'approve',
    });
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.0.0',
        status: 'staged',
        content: { instructions: 'You are alpha.' },
      }),
    );
    await activate({
      artifact: buildAgent({
        name: 'alpha',
        version: '1.0.0',
        status: 'staged',
        content: { instructions: 'You are alpha.' },
      }),
      stagedAt: Date.now(),
    });

    // Stage the self-modify candidate.
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
    );
  });

  it('keeps resolveConstructedAgent on the prior version until drain', async () => {
    const ask: SelfModifyAskUser = async () => 'approve';
    configureRuntime({
      cwd: tmpRoot,
      policy: async () => 'reject',
      selfModifyAskUser: ask,
    });

    expect(resolveConstructedAgent('alpha')?.instructions).toBe('You are alpha.');

    await activate({
      artifact: buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
      stagedAt: Date.now(),
    });

    // Disk says active, audit says activated, budget consumed — but
    // the resolver still hands out the prior version because the swap
    // is pending.
    expect(hasPendingSwap('alpha')).toBe(true);
    expect(resolveConstructedAgent('alpha')?.instructions).toBe('You are alpha.');

    const drained = drainPendingSwaps();
    expect(drained).toEqual(['alpha']);
    expect(hasPendingSwap('alpha')).toBe(false);
    expect(resolveConstructedAgent('alpha')?.instructions).toBe(
      'You are alpha. Be thorough.',
    );
  });
});

describe('activate() — self-modify budget edge case', () => {
  it('rejects with budget-exhausted when budget was consumed between stage and activate', async () => {
    await persistArtifactDirect(
      buildAgent({ name: 'alpha', version: '1.0.0', status: 'active' }),
    );
    await persistArtifactDirect(
      buildAgent({
        name: 'alpha',
        version: '1.1.0',
        status: 'staged',
        sourceAgent: 'alpha',
        content: { instructions: 'You are alpha. Be thorough.' },
      }),
    );

    // Burn the entire budget AFTER staging — race between two
    // self-modify cycles can leave the activate boundary with zero
    // remaining slots even though stage time saw budget>0.
    for (let i = 0; i < DEFAULT_SELF_MODIFY_BUDGET; i += 1) {
      await consumeBudget('alpha', { cwd: tmpRoot });
    }

    const ask: SelfModifyAskUser = vi.fn(async (): Promise<'approve' | 'reject'> => 'approve');
    configureRuntime({
      cwd: tmpRoot,
      policy: async () => 'reject',
      selfModifyAskUser: ask,
    });

    await expect(
      activate({
        artifact: buildAgent({
          name: 'alpha',
          version: '1.1.0',
          status: 'staged',
          sourceAgent: 'alpha',
          content: { instructions: 'You are alpha. Be thorough.' },
        }),
        stagedAt: Date.now(),
      }),
    ).rejects.toThrow(/budget exhausted between stage and activate/);

    // ask-user was NOT called (budget rejected before reaching it).
    expect(ask).not.toHaveBeenCalled();

    // Audit entry recorded.
    const audit = await readAuditEntries({ cwd: tmpRoot, agentName: 'alpha' });
    expect(audit).toHaveLength(1);
    expect(audit[0]!.event).toBe('self_modify_rejected');
    expect(audit[0]!.rejectRule).toBe('budget-exhausted');
  });
});
