/**
 * KodaX - 极致轻量化 Coding Agent
 *
 * 根入口文件 - 代理到 monorepo packages
 */

// Core API - 从 @kodax-ai/coding 重新导出
export * from '@kodax-ai/coding';
export {
  Client,
  createDefaultCodingAgent,
  createKodaXTaskRunner,
  KodaXClient,
  runKodaX,
  runManagedTask,
  startKodaX,
} from './trusted-coding-entry.js';
export {
  ACP_LOG_LEVELS,
  AcpLogger,
  resolveAcpLogLevel,
  type AcpLogLevel,
} from './acp_logger.js';
export {
  AcpEventEmitter,
  type AcpEventSink,
  type AcpRuntimeEvent,
} from './acp_events.js';
export {
  createKodaXRuntime,
  acquireKodaXInlineOwner,
  connectKodaXRuntime,
  enableKodaXDaemonOwner,
  getKodaXRuntimeOwnerPolicy,
  getKodaXRuntimeOwnerState,
  handleRuntimePermissionRequest,
  parseRuntimeEvent,
  RuntimePermissionScopeUpgradeRequiredError,
  RuntimeTransportBoundaryError,
  setKodaXRuntimeOwnerMode,
  settleKodaXRuntimeExit,
  waitForRuntimeDaemonShutdown,
} from './sdk-runtime.js';
export type {
  RuntimeExactCallPermissionMatcher,
  RuntimeExactCommandPermissionMatcher,
  RuntimeExactPathPermissionMatcher,
  RuntimePermissionHostPlatform,
  RuntimePermissionMatcher,
} from './runtime-permission-scope.js';
export type {
  CreateKodaXRuntimeOptions,
  KodaXDaemonRuntime,
  KodaXRuntime,
  KodaXRuntimeMode,
  RuntimeInlineOwnerHandle,
  RuntimeOwnerPolicyState,
  RuntimeOwnerIdentity,
  RuntimeOwnerState,
  RuntimeCreateSessionInput,
  RuntimeEvent,
  RuntimeEventEnvelope,
  RuntimeEventParseResult,
  RuntimeEventPayloadMap,
  RuntimeEventFilter,
  RuntimeEventListener,
  RuntimeTypedEventListener,
  RuntimeEventReplayFilter,
  RuntimeEventService,
  RuntimeEventType,
  RuntimeTypedEvent,
  RuntimeTextDeltaEventPayload,
  RuntimeThinkingFinishedEventPayload,
  RuntimeToolStartedEventPayload,
  RuntimeToolProgressEventPayload,
  RuntimeToolFinishedEventPayload,
  RuntimeRunProgressEventPayload,
  RuntimeRunInputQueuedEventPayload,
  RuntimeRunInputDeliveredEventPayload,
  RuntimeDeliveredInterruptInput,
  RuntimeTodoUpdatedEventPayload,
  RuntimeInteractionResolvedEventPayload,
  RuntimeWarningEventPayload,
  RuntimeForkSessionInput,
  RuntimeIdentity,
  RuntimeConnectionService,
  RuntimeConnectionState,
  RuntimeDaemonPreflight,
  RuntimeDaemonManagementService,
  RuntimeDaemonManagementState,
  RuntimeDaemonRollbackInput,
  RuntimeDaemonRollbackResult,
  RuntimeExitSettlement,
  RuntimeExitSettlementBlockReason,
  RuntimeExitSettlementInput,
  RuntimeDaemonShutdownVerification,
  RuntimeDaemonShutdownVerificationInput,
  RuntimeDaemonShutdownVerificationOwner,
  RuntimeDaemonContextOptions,
  RuntimeDaemonKodaXOptions,
  RuntimeDaemonRunService,
  RuntimeDaemonStartRunInput,
  RuntimeKodaXOptions,
  RuntimeLearningService,
  RuntimePermissionRequestInput,
  RuntimePermissionDecision,
  RuntimePermissionPrompt,
  RuntimePermissionPromptContext,
  RuntimePermissionPromptResolution,
  RuntimePermissionFilter,
  RuntimePermissionGrant,
  RuntimePermissionGrantChangedEventPayload,
  RuntimePermissionGrantSuggestion,
  RuntimePermissionRequest,
  RuntimePermissionRespondOptions,
  RuntimePermissionRisk,
  RuntimePermissionScope,
  RuntimePermissionService,
  RuntimeOperationReceipt,
  RuntimeOperationService,
  RuntimeRunFilter,
  RuntimeFailureDetail,
  RuntimeFailureStage,
  RuntimeRunHandle,
  RuntimeRunFailureKind,
  RuntimeRunMode,
  RuntimeRunPhase,
  RuntimeProviderErrorCode,
  RuntimeRunLifecycleError,
  RuntimeRunResult,
  RuntimeRunService,
  RuntimeRunStatus,
  RuntimeRunStopReceipt,
  RuntimeRunStopStatus,
  RuntimeTerminalFact,
  RuntimeRunRequirements,
  RuntimeInterruptInputStatus,
  RuntimeSubmitInput,
  RuntimeSubmitInputResult,
  RuntimeSession,
  RuntimeRunSessionLoadedEventPayload,
  RuntimeSessionLoadedEventPayload,
  RuntimeSessionSettingsUpdatedEventPayload,
  RuntimeUserInputRequestedEventPayload,
  RuntimeSessionFilter,
  RuntimeSessionService,
  RuntimeSessionSettings,
  RuntimeSessionSettingsPatch,
  RuntimeSessionObservationSnapshot,
  RuntimeSessionSummary,
  RuntimeStatusService,
  RuntimeStatusSnapshot,
  RuntimeCredentialLease,
  RuntimeCredentialService,
  RuntimeHostToolInvocationStatus,
  RuntimeHostToolLease,
  RuntimeHostToolService,
  RuntimeSubscription,
  RuntimeTextInput,
  RuntimeUserInputFilter,
  RuntimeUserInputKind,
  RuntimeUserInputRequest,
  RuntimeUserInputResolution,
  RuntimeUserInputService,
  RuntimeTranscript,
  RuntimeWorkflowFilter,
  RuntimeWorkflowListener,
  RuntimeWorkflowService,
  RuntimeWorkflowSnapshot,
  RuntimeWorkflowSummary,
} from './sdk-runtime.js';
export {
  KODAX_ASRT_VERSION,
  doctorKodaXSandbox,
  activateKodaXSandbox,
  getKodaXSandboxSetupGuidance,
  getKodaXSandboxCapability,
  runKodaXSandboxed,
  setupKodaXSandbox,
} from './sdk-sandbox.js';
export type {
  KodaXSandboxDoctorResult,
  KodaXSandboxCapability,
  KodaXSandboxFilesystemPolicy,
  KodaXSandboxNetworkPolicy,
  KodaXSandboxRunInput,
  KodaXSandboxRunResult,
  KodaXSandboxSetupOutcome,
} from './sdk-sandbox.js';
// ACP server API - server `cwd` can pin the session-level executionCwd for prompts and tools.
export { KodaXAcpServer, runAcpServer, type KodaXAcpServerOptions } from './acp_server.js';

// REPL API - 从 @kodax-ai/repl 重新导出
export {
  runInkInteractiveMode,
  runInteractiveMode,
} from './trusted-repl-entry.js';
export {
  type InkREPLOptions,
  processSpecialSyntax,
  type RepLOptions,
  InteractiveContext,
  createInteractiveContext,
  touchContext,
  parseCommand,
  executeCommand,
  BUILTIN_COMMANDS,
  type Command,
  type CommandCallbacks,
  type CurrentConfig,
  getVersion,
  KODAX_VERSION,
  getProviderModel,
  getProviderList,
  isProviderConfigured,
  hydrateProcessEnvFromShell,
  loadConfig,
  loadAutoModeSettings,
  resolveAutoModeSettings,
  type AutoModeSettings,
  type ResolvedAutoModeSettings,
  type ResolveAutoModeSettingsInput,
  prepareRuntimeConfig,
  registerConfiguredCustomProviders,
  saveConfig,
  getGitRoot,
  rateLimitedCall,
  KODAX_DIR,
  KODAX_SESSIONS_DIR,
  KODAX_CONFIG_FILE,
  FileSessionStorage,
  type PreparedSessionAppendBaseline,
  type PreparedSessionTailDelta,
} from '@kodax-ai/repl';
